apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: php
        image: monikarani1/php1:latest
        ports:
        - containerPort: 80     
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
  - nodePort: 31001
    targetPort: 80
    port: 8080
    protocol: TCP
  selector:
    app: demo-app
  type: NodePort

